### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by karan** [mrbbp/wooden-smart-toy#1]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by mrbbp** [comment]
Hello Karan,
how to add licence? in the code?
Sorry i'm newb ;)
I prefer GPL one.

**Comment by mrbbp** [comment]
ok it's done. Thanks for the advice..
regards
